/usr/lib/ruby/vendor_ruby/restclient/abstract_response.rb:74:in `return!': 500 Internal Server Error (RestClient::InternalServerError)
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:495:in `process_result'
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:421:in `block in transmit'
	from /usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:413:in `transmit'
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:176:in `execute'
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:41:in `execute'
	from /usr/lib/ruby/vendor_ruby/restclient.rb:65:in `get'
	from /usr/bin/g5k-backend-sudo:66:in `<main>'
/bin/sh: 2: mvn: not found
Traceback (most recent call last):
  File "/home/tdurieux/defects4j4repair/script/runner/local/LocalRunner.py", line 42, in run
    task.run()
  File "/home/tdurieux/defects4j4repair/script/runner/RepairTask.py", line 27, in run
    return self.tool.repair(self)
  File "/home/tdurieux/defects4j4repair/script/core/repair_tools/Astor.py", line 43, in repair
    if bug.compliance_level() > 7:
  File "/home/tdurieux/defects4j4repair/script/core/Bug.py", line 62, in compliance_level
    return self.benchmark.compliance_level(self)
  File "/home/tdurieux/defects4j4repair/script/core/benchmarks/Bears.py", line 203, in compliance_level
    info = self._get_project_info(bug)
  File "/home/tdurieux/defects4j4repair/script/core/benchmarks/Bears.py", line 73, in _get_project_info
    info = json.loads(subprocess.check_output(cmd, shell=True))
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'cd /tmp/Cardumen_Bears_INRIA-spoon_271649592-272084174;
mvn com.github.tdurieux:project-config-maven-plugin:1.0-SNAPSHOT:info -q;
' returned non-zero exit status 127
