/usr/lib/ruby/vendor_ruby/restclient/abstract_response.rb:74:in `return!': 500 Internal Server Error (RestClient::InternalServerError)
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:495:in `process_result'
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:421:in `block in transmit'
	from /usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:413:in `transmit'
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:176:in `execute'
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:41:in `execute'
	from /usr/lib/ruby/vendor_ruby/restclient.rb:65:in `get'
	from /usr/bin/g5k-backend-sudo:66:in `<main>'
/bin/sh: 2: mvn: not found
Traceback (most recent call last):
  File "/home/tdurieux/defects4j4repair/script/core/runner/local/LocalRunner.py", line 41, in run
    task.run()
  File "/home/tdurieux/defects4j4repair/script/core/runner/RepairTask.py", line 30, in run
    return self.tool.repair(self)
  File "/home/tdurieux/defects4j4repair/script/core/repair_tools/Nopol.py", line 40, in repair
    classpath = ":".join(bug.bin_folders() + bug.test_bin_folders())
  File "/home/tdurieux/defects4j4repair/script/core/Bug.py", line 53, in bin_folders
    return self.benchmark.bin_folders(self)
  File "/home/tdurieux/defects4j4repair/script/core/benchmarks/BugDotJar.py", line 145, in bin_folders
    info = self._get_project_info(bug)
  File "/home/tdurieux/defects4j4repair/script/core/benchmarks/BugDotJar.py", line 97, in _get_project_info
    info = json.loads(subprocess.check_output(cmd, shell=True))
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'cd /tmp/DynaMoth_Bugs.jar_Wicket_240ab3c3;
mvn com.github.tdurieux:project-config-maven-plugin:1.0-SNAPSHOT:info -q;
' returned non-zero exit status 127
