ERROR: node is shared with other users (all users: tdurieux enuriyev). sudo-g5k is not allowed.
/bin/sh: 2: mvn: not found
Traceback (most recent call last):
  File "/home/tdurieux/defects4j4repair/script/runner/local/LocalRunner.py", line 42, in run
    task.run()
  File "/home/tdurieux/defects4j4repair/script/runner/RepairTask.py", line 27, in run
    return self.tool.repair(self)
  File "/home/tdurieux/defects4j4repair/script/core/repair_tools/Astor.py", line 46, in repair
    classpath = bug.classpath(repair_task)
  File "/home/tdurieux/defects4j4repair/script/core/Bug.py", line 59, in classpath
    return self.benchmark.classpath(repair_task)
  File "/home/tdurieux/defects4j4repair/script/core/benchmarks/BugDotJar.py", line 164, in classpath
    info = self._get_project_info(repair_task.bug)
  File "/home/tdurieux/defects4j4repair/script/core/benchmarks/BugDotJar.py", line 96, in _get_project_info
    info = json.loads(subprocess.check_output(cmd, shell=True))
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'cd /tmp/jKali_Bug_dot_jar_Jackrabbit-Oak_b896c926;
mvn com.github.tdurieux:project-config-maven-plugin:1.0-SNAPSHOT:info -q;
' returned non-zero exit status 127
